controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  diablo_balance_controller:
    type: balance/DiabloBalanceController
    left_wheel:
      joint: left_j3
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    right_wheel:
      joint: right_j3
      pid: { p: 0.8, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_follow: { p: 0, i: 0, d: 0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_left_leg: { p: 1000, i: 0, d: 600, i_clamp_max: 100.0, i_clamp_min: -100.0, antiwindup: true, publish_state: true }
    pid_right_leg: { p: 1000, i: 0, d: 600, i_clamp_max: 100.0, i_clamp_min: -100.0, antiwindup: true, publish_state: true }
    pid_theta_diff: { p: 40, i: 0.0, d: 0.01, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_roll: { p: 200.0, i: 0, d: 30, i_clamp_max: 15.0, i_clamp_min: -15.0, antiwindup: true, publish_state: true }
    pid_center_gravity: { p: 0.0, i: 0, d: 0, i_clamp_max: 400.0, i_clamp_min: -400.0, antiwindup: true, publish_state: true }
    pid_length_diff: { p: 0, i: 0, d: 0, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: true }
#   Only use for sit down mode
    pid_sit_down_left_theta: { p: 200, i: 20, d: 5.0, i_max: 10.0, i_min: -10.0, antiwindup: true, publish_state: true }
    pid_sit_down_right_theta: { p: 200, i: 20, d: 5.0, i_max: 10.0, i_min: -10.0, antiwindup: true, publish_state: true }
    leg_protect_angle: 0.9  #0.9
    pitch_protect_angle: 1.1 #1.1
    roll_protect_angle: 1.0
    leg_protect_length: 0.02
    ground_support_threshold: 5
    left_vmc_bias_angle: -0.2687
    right_vmc_bias_angle: 0.13433

    gravity_compensation_vel_threshold: 0
    gravity_compensation_pos_threshold: 0

    jump_over_time: 2.0
    p1: -241100
    p2: 170300
    p3: 39310
    p4: 3234



