gazebo:
  delay: 0.0
  imus:
    base_imu:
      frame_id: base_imu
      orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
      angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
      linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
  hybrid_joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  base_vel:
    - baseX
    - baseY
    - baseYaw

gazebo_ros_control:
  pid_gains:
    left_j3:
      p: 3
      i: 0.0
      d: 0.0
    right_j3:
      p: 3
      i: 0.0
      d: 0.0